fiIndexGribs can now read earthfigure and extraKeys from cdmGribReaderConfig new tests included

diff --git a/test/testFiIndexGribs.sh.in b/test/testFiIndexGribs.sh.in
--- a/test/testFiIndexGribs.sh.in
+++ b/test/testFiIndexGribs.sh.in
@@ -33,6 +33,30 @@ else
   exit 1;
 fi
 
+rm -f test.grib1.grbml2
+../src/binSrc/fiIndexGribs -f --i @top_srcdir@/test/test.grb1 --readerConfig=@top_srcdir@/test/cdmGribReaderConfig_newEarth.xml -a test.grb1.grbml2
+if [ $? != 0 ]; then
+  echo "failed writing test.grb1.grbml2 with readerConfig"
+  exit 1
+fi
+if [ ! -f test.grb1.grbml2 ]; then
+  echo "failed writing test.grb1.grbml2 with readerConfig"
+  exit 1
+fi
+if grep -q localDefinitionNumber test.grb1.grbml2; then
+  echo "success"
+else
+  echo "no localDefinitionNumber in test.grb1.grbml2"
+  exit 1;
+fi
+if ! diff -q test.grb1.grbml test.grb1.grbml2 ; then
+  echo "success"
+else
+  echo "earthFigure not different between test.grb1.grbml and test.grb1.grbml2"
+  exit 1;
+fi
+rm -f test.grb1.grbml2
+
 # read grbml with fimex
 ../src/binSrc/fimex --input.file=test.grb1.grbml --input.config=@top_srcdir@/share/etc/cdmGribReaderConfig.xml --input.printNcML | grep x_wind_10m > /dev/null
 if [ $? != 0 ]; then
